const actionTypes = {
	ADD_RECIPE: "ADD_RECIPE",
	BEGIN_ADD_RECIPE: "BEGIN_ADD_RECIPE",
	CHANGE_PAGE: "CHANGE_PAGE",
	CHANGE_CREATING_RECIPE: "CHANGE_CREATING_RECIPE",
	DELETE_RECIPE: "DELETE_RECIPE",
	CANCEL_ADD_RECIPE: "CANCEL_ADD_RECIPE",
	INIT_RECIPES: "INIT_RECIPES",
	SEARCH_RECIPE_NAMES: "SEARCH_RECIPE_NAMES",
	VIEW_RECIPE: "VIEW_RECIPE",
}

Object.freeze(actionTypes);

export default actionTypes;