const actionTypes = {
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  HIDE_MODAL: 'HIDE_MODAL',
  INIT_RECIPES: 'INIT_RECIPES',
  SEARCH_RECIPE_NAMES: 'SEARCH_RECIPE_NAMES',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SHOW_MODAL: 'SHOW_MODAL'
};

Object.freeze(actionTypes);

export default actionTypes;
