const actionTypes = {
	ADD_DIRECTION: "ADD_DIRECTION",
	ADD_INGREDIENT: "ADD_INGREDIENT",
	ADD_RECIPE: "ADD_RECIPE",
	BEGIN_ADD_RECIPE: "BEGIN_ADD_RECIPE",
	BEGIN_EDIT_RECIPE: "BEGIN_EDIT_RECIPE",
	CANCEL_ADD_RECIPE: "CANCEL_ADD_RECIPE",
	CHANGE_CREATING_RECIPE: "CHANGE_CREATING_RECIPE",
	CHANGE_DIRECTION: "CHANGE_DIRECTION",
	CHANGE_INGREDIENT: "CHANGE_INGREDIENT",
	CHANGE_PAGE: "CHANGE_PAGE",
	CHANGE_RECIPE_DESCRIPTION: "CHANGE_RECIPE_DESCRIPTION",
	CHANGE_RECIPE_NAME: "CHANGE_RECIPE_NAME",
	DELETE_DIRECTION: "DELETE_DIRECTION",
	DELETE_INGREDIENT: "DELETE_INGREDIENT",
	DELETE_RECIPE: "DELETE_RECIPE",
	END_EDIT_RECIPE: "END_EDIT_RECIPE",
	INIT_RECIPES: "INIT_RECIPES",
	MOVE_DIRECTION_DOWN: "MOVE_DIRECTION_DOWN",
	MOVE_DIRECTION_UP: "MOVE_DIRECTION_UP",
	MOVE_INGREDIENT_DOWN: "MOVE_INGREDIENT_DOWN",
	MOVE_INGREDIENT_UP: "MOVE_INGREDIENT_UP",
	SEARCH_RECIPE_NAMES: "SEARCH_RECIPE_NAMES",
	VIEW_RECIPE: "VIEW_RECIPE"
};

Object.freeze(actionTypes);

export default actionTypes;
